### ISSUE TITLE
Syslog4j dead?

### ISSUE THREAD

**Issue by robertvazan** [papertrail/logback-syslog4j#8]
This project uses old syslog4j from maven, which is at version 0.9.30. No new versions of syslog4j are available in maven under "org.syslog4j" even though 0.9.46 is available as JAR download from http://syslog4j.org/

There's https://github.com/Graylog2/syslog4j-graylog2 from https://www.graylog.org/ which continues where original syslog4j stopped and it has maven repo at http://mvnrepository.com/artifact/org.graylog2/syslog4j with recent releases.

Could you try upgrading this project to either 0.9.46 or the graylog port?

Anyway, original syslog4j is dead and graylog fork doesn't aim to deliver any production quality. So what do we use with papertrail now?

**Comment by eric239** [comment]
Pretty late response, but anyhow...
Leon (Papertrail customer service) pointed me to their (PT) [custom version of syslog4j jar](https://www.dropbox.com/s/ns71z0gzp16ys8t/syslog4j-0.9.47-Papertrail.jar?dl=1) which is not the ideal outcome as there is no corresponding source and the jar is not available in a public maven repo, but still better than dead syslog4j project itself.

How about adopting syslog4j project, papertrail? Or at least publishing the source with your changes in a GH repo like graylog did.

**Comment by troy** [comment]
All, just a note regarding this:

> How about adopting syslog4j project, papertrail? 

I'm afraid we don't have the expertise, time, or release/repo control to do this. Just creating this syslog4j adaptor itself was a non-trivial amount of time and effort to test, mostly for community good rather than because it had any kind of benefit for Papertrail (it didn't; we just wanted it to exist and saw an opportunity). So, while I appreciate that "How about adopting syslog4j project" was written in good spirit, that's not practical for us to do nor reasonable to request.

Regarding upgrading to a newer or different syslog4j, pull requests doing this are gladly accepted. Obviously if Papertrail's team has time and interest, we'd try to do so as well, but there's no reason to block on that.
